leads/urls.py
from django.urls import path
from .views import *

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name="lead-list"),
    path('<int:pk>/', LeadDetailView.as_view(), name="detallar"),
    path('<int:pk>/update_detail/', LeadUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name="delete"),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name="assign-agent"),
    path('<int:pk>/lead-category-update/', LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path('create-leads/', LeadCreateView.as_view(), name="lead-create"),
    path('categories/', CategoryListView.as_view(), name="categories"),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name="category-detail"),
] 

sucrm/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)
from django.urls import path, include
from leads.views import HomeView, SigupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view()),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('signup/', SigupView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('password-reset-view/', PasswordResetView.as_view(), name="password_reset_view"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-complate/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('password-tiklash/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('logout/', LogoutView.as_view(), name="logout")
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    ismi = models.CharField(max_length=20)
    familiyasi = models.CharField(max_length=20)
    yoshi = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name='leads', null=True,  blank=True, on_delete=models.SET_NULL)
    izoh = models.TextField()
    sana = models.DateTimeField(auto_now_add=True)
    telefon = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return str(self.familiyasi)

class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


def post_user_yaratish_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_yaratish_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, Agent

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "ismi",
            "familiyasi",
            "yoshi",
            "agent",
            'izoh',
            'telefon',
            'email',  
        )

class LeadForm(forms.Form):
    ismi = forms.CharField(max_length=20)
    familiyasi = forms.CharField(max_length=20)
    yoshi = forms.IntegerField(min_value=0)

class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset = Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import *
from .models import *
from .forms import *
from agents.mixins import OrganiserAndLoginRequiredMixin

class SigupView(CreateView):
    template_name = "registration/signup.html"
    form_class = NewUserForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")

class HomeView(TemplateView):
    template_name = "home.html"

class LeadListView(LoginRequiredMixin, ListView):
    template_name = "leads/leads_list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = queryset.filter(agent__user = self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile, 
                agent__isnull=True
            )
            context.update({
                "unassigned_leads": queryset
            })
        return context

class LeadDetailView(OrganiserAndLoginRequiredMixin, DetailView):
    template_name = "leads/leads_detail.html"
    queryset = Lead.objects.all()
    context_object_name = "lead"

class LeadCreateView(OrganiserAndLoginRequiredMixin, CreateView):   
    template_name = "leads/leads_create.html"
    form_class = LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        send_mail(
            subject="Bu lead yaratilingan",
            message="Yangi lead yarat",
            from_email="test@test.com",
            recipient_list=["test2@test.com"],
        )
        return super(LeadCreateView, self).form_valid(form)

class LeadUpdateView(OrganiserAndLoginRequiredMixin, UpdateView):
    template_name = "leads/leads_update.html"
    queryset = Lead.objects.all()
    form_class = LeadModelForm
    
    def get_success_url(self):
        return reverse("leads:lead-list")

class LeadDeleteView(OrganiserAndLoginRequiredMixin, DeleteView):
    template_name = "leads/leads_delete.html"
    queryset = Lead.objects.all()
    
    def get_success_url(self):
        return reverse("leads:lead-list")

class AssignAgentView(OrganiserAndLoginRequiredMixin, FormView):
    template_name = "leads/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs
    
    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "leads/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation = user.agent.organisation
            )
        context.update({
            "unassigned_category_leads": queryset.filter(category__isnull=True).count()
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation = user.userprofile
            )
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation
            )
        return queryset

class CategoryDetailView(LoginRequiredMixin, DeleteView):
    template_name = "leads/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation = user.userprofile
            )
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation
            )
        return queryset

class LeadCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "leads/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(
                organisation = user.userprofile
            )
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation
            )
        return queryset

    
    def get_success_url(self):
        return reverse("leads:lead-list")
        

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ lead.ismi }} {{ lead.familiyasi }}</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">Agentni belgilang</h1>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Tasdiqlash</button>
            </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            Ushbu fanga qatnashuvchi o'quvchilar ma'lumotlari
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">Ismi</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">Soni</th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
                <tr>
                    <td class="px-4 py-3">
                      <a class="hover:text-blue-500" href="{% url 'leads:detallar' lead.pk %}">{{ lead.ismi }}</a>
                    </td>
                    <td class="px-4 py-3">O'quvchi</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Fanlar</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            Barcha fanlar ro'yxati
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">Soni</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3">Aniqlanmagan</td>
                <td class="px-4 py-3">{{ unassigned_category_leads }}</td>
            </tr>
            {% for category in category_list %}
                <tr>
                    <td class="px-4 py-3">
                      <a class="hover:text-blue-500" href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                    </td>
                    <td class="px-4 py-3">Barafsil</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:detallar' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Ma'lumotlar
                </a>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Fani
                </a>
                <a href="{% url 'leads:update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    O'zgartirish
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">O'zgartirish</button>
            </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/leads_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}">Ro'yhatga qaytish</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Yangi mijoz</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Qo'shish
        </button>
    </form>
</div>

{% endblock content %}

leads/templates/leads/leads_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}">Ortga qaytish</a>
    </div>
    <h1 class="text-3xl text-gray-800">O'chirishga aminmisiz</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">O'chirish</button>
    </form>
</div>
{% endblock content %}

leads/templates/leads/leads_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Mijoz</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.ismi }} {{ lead.familiyasi }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:detallar' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Ma'lumotlar
                </a>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Fani
                </a>
                <a href="{% url 'leads:update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    O'zgartirish
                </a>    
            </div>
            <p class="leading-relaxed mb-4">{{ lead.izoh }}</p>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Yoshi</span>
                <span class="ml-auto text-gray-900">{{ lead.yoshi }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ lead.email }}</span>
            </div>
            <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                <span class="text-gray-500">Phone Number</span>
                <span class="ml-auto text-gray-900">{{ lead.telefon }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/leads_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Mijozlar</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:categories' %}">
                    Fanlarni aniqlash
                </a>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">
                    Yangi mijoz qo'shish
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Ismi
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Familiyasi
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Yoshi
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Telefon raqami
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Fani
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">O'zgartirish</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    {{ lead.ismi }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.familiyasi }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.yoshi }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.telefon }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if lead.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ lead.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Aniqlanmagan
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        O'zgartirish
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Agenti nomalum</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.ismi }} {{ lead.familiyasi }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.izoh }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Agentni aniqlash
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

leads/templates/leads/leads_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:detallar' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Ma'lumotlar
                </a>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Fani
                </a>
                <a href="{% url 'leads:update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    O'zgartirish
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">O'zgartirish</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'leads:delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    O'chirish
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}